### ISSUE TITLE
Нужна помощь

### ISSUE THREAD

**Issue by zarochintsev** [MLSDev/AppRouter#1]
```
[AppRouter][Presenter] failed to find navigation controller (using target provider) to push on.
```

Что с этим делать?

**Comment by sinarionn** [comment]
Прости за пазу ответа. 

Как и значится в ошибке - что бы произвести пуш контроллера, нужен   UINavigationController и таргет, на который ты используешь, его не содержит (по умолчанию таргетом считается текущий верхний контроллер, что б изменить таргет используй метод `on(_ provider: () throws -> UIViewController)`)

Сложно подсказать не зная контекст использования. Возможно ты хочешь что б твой контроллер был обрамлен в UINavigationController и стал рутовым или был запрезенчен? Тогда нужно делать не пуш, а обрамлять и презентить:
`ControllerType.presenter().embedInNavigation().present()`
либо делать рутовым:
`ControllerType.presenter().embedInNavigation().setAsRoot()`

Если же все-таки необходимость произвести пуш, то укажи явно таргет, который сам будет UINavigationController'ом, либо который будет внутри него:
`ControllerType.presenter().on{ specificControllerWithNavigation }.push()`
